Get task uuid from notebook metadata
platiagro/jupyterlab-extension pull request #13
Opened 2020-08-14 17:06 UTC by shiguemi32

2020-08-17 14:24 UTC, fberanizo requested changes

2020-08-17 14:24 UTC, fberanizo commented on jupyterlab_extension/hooks.py
>      match = re.search(r"tasks/(.*?)/(Experiment|Deployment).ipynb", os_path)
@shiguemi32 como o group(1) não é mais utilizado, pode tirar ele do regex:
```python
    match = re.search(r"tasks/.*?/(Experiment|Deployment).ipynb", os_path)
```

2020-08-17 14:24 UTC, fberanizo commented on jupyterlab_extension/hooks.py
> +                else:
@shiguemi32 aqui tem 4 níveis de indentação. O ideal é no máximo 3:
```python
 if match: (1)
...
    if task_id is not None: (2)
        try: (3)
            if notebook_type == "Experiment": (4)
```

2020-08-17 16:40 UTC, shiguemi32 commented on jupyterlab_extension/hooks.py
>      match = re.search(r"tasks/(.*?)/(Experiment|Deployment).ipynb", os_path)
Feito

2020-08-17 16:40 UTC, shiguemi32 commented on jupyterlab_extension/hooks.py
> +                else:
Feito

2020-08-18 14:21 UTC, fberanizo approved these changes
LGTM

2020-08-18 14:21 UTC, merged